### ISSUE TITLE
not support swift ui 

### ISSUE THREAD

**Issue by EslamAwad77** [SimformSolutionsPvtLtd/SSSpinnerButton#54]

**Comment by bhargavbajani-simformsolutions** [comment]
@EslamAwad77  We have a different Library for specially swiftUI. 

[SSSwiftUISpinnerButton](https://github.com/SimformSolutionsPvtLtd/SSSwiftUISpinnerButton)
 

Check out our other Libraries
[🗂 Simform Solutions Libraries→](https://github.com/SimformSolutionsPvtLtd/Awesome-Mobile-Libraries)
